### ISSUE TITLE
I have to do one kodi addon can yu plz contct me 

### ISSUE THREAD

**Issue by ajdeshmane0007** [vargalex/plugin.video.filmpapa#1]
I also want to do a kodi addons bt i have less knowledge about coding plz contact me if possible

**Comment by vargalex** [comment]
Hi!

You can send me a message to vargagab@gmail.com.

**Comment by ajdeshmane0007** [comment]
Plz share whatsapp because i have not much active on mail so plzz contact me here 

wa.me/917249727257?text=hi_from_github

**Comment by vargalex** [comment]
Sorry, but I have not whatsapp...

Gabor Varga

Mr Cool Aj ***@***.***> ezt írta (időpont: 2022. szept. 23.,
P, 13:21):

**Comment by ajdeshmane0007** [comment]
Telegram??

**Comment by ajdeshmane0007** [comment]
T.me/Mrcoolnox

**Comment by ajdeshmane0007** [comment]
I have to share you idea for making one extension if you are interested to do then dm me its really helpful if you can do...

**Comment by ajdeshmane0007** [comment]
I have email you plz check
