### ISSUE TITLE
A Filmek nem indulnak el egyből

### ISSUE THREAD

**Issue by tibikepc** [vargalex/plugin.video.filmpapa#3]
Hello,nem tudnád,feltöltenni az előbbi verziót is?
A mostani verzióval az a gond,hogy nem indulnak egyből el a filmek,tehát ha rá kattintok az adott film ikonjára,nem indul el egyből a film hanem át dobb egy másik könyvtárban,és ott újból rá kell katintani (Lejátszó 1 vagy Lejátszó 2),sajnos apukám már idős és minél egyszerűbb volt neki annál jobb..
Köszi előre is.

**Comment by vargalex** [comment]
Szia!

Ez nem egy hiba, direkt azért lett benne, mert észrevettem, hogy egy filmnek lehet több forrása is. A korábbi verziók a [movieshark repo-ban elérhetőek](https://repo.mvshrk.xyz/plugins/plugin.video.filmpapa/) direkt letöltéssel.

**Comment by tibikepc** [comment]
Értem,köszi a segítséget,még lenne egy kérdésem,tudom,hogy nem ide tartozik,de ha már válaszoltál megkérdezem itt,nem tudnál esetleg,elementumban egy újabb magyar nyelvű torrent oldalt betenni? Nagyon jó lenne mert ncoron például nincsenek fent azok a filmek amik csak mozis formátumban vannak megjelenve még,a Bestcore vagy a Ztracker.cc torrent oldalak nagyon szuperek lennének ha be kerülnének.

**Comment by vargalex** [comment]
Az elementum addon fejlesztője nem rakja be?

**Comment by tibikepc** [comment]
Hát,útmutatót küld,hogy hogyan kell berakni,viszont én nagyon sokat próbálgattam,de nem sikerül,az igazság az,hogy nem is értek hozzája.Nagyon megköszöném ha megtudnád csinálni.

**Comment by vargalex** [comment]
Ha időm lesz, ránézek.

**Comment by tibikepc** [comment]
Rendben,köszönöm szépen előre is.
